### ISSUE TITLE
Undocumented Environment Params / Unexpected format behavior

### ISSUE THREAD

**Issue by alexmerm** [Jeeaaasus/youtube-dl#100]
There are a few environment parameters that are used in root/app/youtube-dl/youtube-dl.sh that are not documented in the README file. Most are harmless except for `youtubedl_args_format` which changes the format from yt-dlp's default to `((bv*[fps>30]/bv*)[height<=$youtubedl_quality]/(wv*[fps>30]/wv*)) + ba / (b[fps>30]/b)[height<=$youtubedl_quality]/(w[fps>30]/w)` whenever it is not set.   Additionally, when you set the `youtubedl_args_format` parameter, it doesn't actually change the format argument for yt-dlp due to the way .sh file is written.

**Comment by Jeeaaasus** [comment]
I don't get the point of this issue. Yes, there are many variables used as part of the logic and they will never be mentioned in the README because they are not meant to be modified by the user.

Specially `youtubedl_args_format` is used as a feature flag to provide the user with a format value if they have not specified one already. I could have just put it in the default args.conf but as I expect the majority of users to customize this file, I did not want to do that because then I would not be able to update the format value.
