### ISSUE TITLE
 ERROR: Join this channel to get access to members-only content like this video, and other exclusive perks.

### ISSUE THREAD

**Issue by CappiSteijns** [Jeeaaasus/youtube-dl#40]
Hi,

Trying to download sub only videos, when adding --cookies cookies.txt or --cookies cookies or --cookies /volume1/docker/youtube/cookies.txt to the ##args I will keep getting the same error (yes i am subbed to the channel).

It does work when I use the --cookies on windows.

Hope to get some help:)

**Comment by Jeeaaasus** [comment]
Hello @CappiSteijns! :)

I'm not 100% certain but I believe you have the parameter a tiny bit wrong.
Inside the container the folder `/config/` is where the config files are stored, and it sounds like you've mounted that folder to `/volume1/docker/youtube/` and probably where you put your cookies.txt.

Because the container sees this folder as being `/config/` the parameter should be `--cookies /config/cookies.txt`

Hope that was the problem! Otherwise I'll have to investigate. :)

**Comment by CappiSteijns** [comment]
hi @Jeeaaasus,

Thanks you so much for your thoughtful thinking and helping!:)
your solution `--cookies /config/cookies.txt` worked like a charm.

My config files for youtube_dl are stored at `/volume1/Config/youtube dl`. Adding `--cookies /config/cookies.txt` to the `args.conf.` file under `## args` did the job.

Thank you, will be using this very often!
