### ISSUE TITLE
Help with samba mount to storage the downloads

### ISSUE THREAD

**Issue by cruix89** [Jeeaaasus/youtube-dl#78]
hi guys

i facing a problem with my server
i using the docker in ubuntu server, but i storage the downloads in a TrueNAS server with samba share
i mount the share folder using the cifs in the fstab mounting in the "/srv/truenas/" folder
in the script i set to save files in "/srv/truenas/" and docker works normally when the fstab mount the folder in start
the problem is when the TrueNAS down or the ubuntu server start alone or first than TrueNAS server
the fstab mount fail becase dont find the network share and the docker and the script start saving the downloads in the local disk of ubuntu server and not in the NAS share, because the system understand the "/srv/TrueNAS" with a local disk now and save the files in the local hard drive

some suggestion to fix the struture?
i apreciate the help
thanks you very much

**Comment by Jeeaaasus** [comment]
Hi, I just wanted to let you know I also have had these kinds of issues when my NAS software (same hypervisor but different vm) starts after my dockerhost or docker is started before the cifs mount in fstab. Also the same kinda setup with cifs mounting in ubuntu.

I don't know how to solve this or what ways to mitigate .. open to ideas.

I know there's native support in docker to mount nfs/cifs share directly as volumes, never tried it though.

[Here's](https://phoenixnap.com/kb/nfs-docker-volumes) a guide with nfs, I think it's the same process with cifs, it involves creating a volume with the share connection and then using that volume in your container. I have no idea if this suffers from the same kind of issues but maybe you didn't know about this and it's worth a try? 

Otherwise maybe I could do some checks on the download location.. 

Anyway I am also interested in this issue, please let me know if you try this approach and how it goes! 🙂

**Comment by cruix89** [comment]
hey Jeasus , thanks for suport,

i trying find some solution with autofs, i see that autofs is diferent than cifs/nfs, when the mount is required , automaticaly autofs mount the folder. i dont sure if works in this way
this mount is a bit complex to me im learning about, dont find a good way yet.

you know some about this?

thanks boss

**Comment by Jeeaaasus** [comment]
Nope 🙂
