### ISSUE TITLE
Consider changing SponsorBlock to remove all

### ISSUE THREAD

**Issue by chriscn** [Jeeaaasus/youtube-dl#83]
Especially when archiving a Youtube channel it would be nice for all the sponsors to be removed.

`--sponsorblock-remove all`

Wondered your thoughts?

**Comment by Jeeaaasus** [comment]
My reasons for only having `--sponsorblock-mark 'all'` as the default configuration setting is threefold.
1. I don't want the default behaviour to change the video experience in any way.
2. If `--sponsorblock-remove 'all'` is used then the resulting video will not playback correctly with some media players because the key-frames are desynced. To fix this I would also need to tell yt-dlp to re-encode all videos and that takes a lot of time and can degrade the quality.
3. The default is just that. It's extremely easy to change the default configuration to your liking.
