### ISSUE TITLE
Channels auto download not work

### ISSUE THREAD

**Issue by mm10079** [Jeeaaasus/youtube-dl#88]
The URL is set in the Channels.txt, but automatic downloading is not enabled.

System: Truenas Scale 22.12.3.2
Docker environment: 
- youtubedl_interval: 1h
- youtubedl_subscriptions: true
![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/53858ab8-3ae1-4f25-a296-91eb123292d4)
version: jeeaaasustest/youtube-dl:latest

**Comment by Jeeaaasus** [comment]
Welcome @mm10079, 
Could you please post what the logs say the first 5 minutes after creating your container? :)
Also please use environment variable `youtubedl_debug=true`.

**Comment by mm10079** [comment]
> 

![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/bca6e7f7-b4a5-449a-befa-713416da880d)
![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/329ac1fb-419e-4f90-aed4-d390b77e6df8)

**Comment by Jeeaaasus** [comment]
Hmm, you might be the first one to try the image on Truenas Scale. (I really like the idea and really need to try it out)

Could you try the following:
Firstly it seems it's maybe the webserver that is breaking, try `youtubedl_webui=false` also have you specified a non-default `youtubedl_webuiport`?

Found some things online indicating that you need to increase your host operating systems `fs.inotify`:
`sysctl -a | grep fs.inotify.max_user_`

By running:
`sysctl -w fs.inotify.max_user_watches=100000`
`sysctl -w fs.inotify.max_user_instances=100000`

**Comment by mm10079** [comment]
Closing youtubedl_webui did not resolve the issue. The youtubedl_webuiport is not using the default port. Thank you for providing the method to extend the log. After inspecting the log, I noticed that the /app folder is being persisted. However, the urls.temp file disappears after one operation, even when granting it 777 permissions, an authorization error still occurs.
(Use ChatGPT translator)
![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/e4d19de7-02f8-42c2-abea-090582981ee4)

**Comment by Jeeaaasus** [comment]
If you have configured the /app folder to be a bind to your host system, the permission failure does makes sense, the user inside the container is called abc and this user doesn't exist outside.

You don't want to make the /app folder persistent, the data in there is totally ephemeral, the only folders you should care about is /config (all your configuration is saved here) and /downloads but at the same time I don't know why I put that temporary file in there instead of /tmp ..

Remove the bind you have defined on /app

**Comment by mm10079** [comment]
After removing the host path for the /app folder, the same error message persists.
![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/496d22f6-bbad-4ebd-91e6-b61f1cb2ae06)
![image](https://github.com/Jeeaaasus/youtube-dl/assets/55078752/647948b1-45b6-4b4d-86c0-53d167a633fc)

**Comment by Jeeaaasus** [comment]
That's really weird.. The container should have no issues writing there but OK.

Seems like you must define both `PUID` and `PGID` to overcome the permission issues.
This error really really really shouldn't happen if you use the environment variables:
`PUID=0` and `PGID=0`

And if that works you should try to find out what ID your standard user in Truenas Scale is, in Linux it's usually `1000` but this might not be the case with Truenas Scale. You typically do not want to use `0` (root user) because then yt-dlp has full root permission and that exposes you to a higher security risk in case of a vulnerability.
Try `PUID=1000` and `PGID=1000` and if that doesn't work try to figure out your normal users ID in your host operating system.

**Comment by Jeeaaasus** [comment]
Great to hear, happy to help.
