### ISSUE TITLE
any way to ignore shorts and lives?

### ISSUE THREAD

**Issue by ItsNoted** [Jeeaaasus/youtube-dl#94]
How can we ignore downloading shorts and live streams? I only want to archive regular videos. Thank you!

**Comment by Jeeaaasus** [comment]
Hi!

Firstly, to only get videos and not any shorts, add "`/videos`" to the end of any channel url, like so: `https://www.youtube.com/channel/UCXXYXXYXXYXX/videos`

Secondly, the [default ](https://github.com/Jeeaaasus/youtube-dl/blob/master/root/config.default/args.conf) configuration is skipping videos that are currently live, in order to also exclude videos that were live, I.E. a previous live-stream, you need to modify your [args.conf ](https://github.com/Jeeaaasus/youtube-dl?tab=readme-ov-file#configure-youtube-dl) to include a `--match-filter` option to deny such videos.

You are looking to specifically exclude both live and previously live videos which would be:
```
--match-filter '!is_live & !was_live
```

However you need to be careful with the `--match-filter` option, as adding several of these will make them all active as "OR" filters, so I recommend only ever having one of these in your configuration at a time.

**Comment by SurvivaLlama** [comment]
Follow up on this - is there a way to only grab videos that at least (specific length of time)?

**Comment by Jeeaaasus** [comment]
@SurvivaLlama, you can find all filterable fields usable with `--match-filter` [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) in the list "The available fields are:"

Looks like you are probably interested in `duration` or `duration_string`, example
```
--match-filter 'duration > 120'
```
Would match videos only longer than 120 seconds. (not tested)

**Comment by SurvivaLlama** [comment]
I can put that command right after the channel right? That way the videos pull from that channel are only the ones that meet or exceed the length requirement.

**Comment by Jeeaaasus** [comment]
Yep, as is described in the README, you can do something like this in your channels.txt

```
https://www.youtube.com/channel/UC0vaVaSyV14uvJ4hEZDOl0Q/videos | --no-match-filter --match-filter ''!is_live & duration > 120'
```
